import {roundNumber,canonical} from '@/app/season';
import {getDb} from '@/db';
import {entries} from '@/db/schema';
import {eq,desc,and} from 'drizzle-orm';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {env} from 'cloudflare:workers';
function admin(req:Request){const secret=(env as unknown as Record<string,string>).LEAGUE_ADMIN_KEY;return !!secret&&req.headers.get('x-league-key')===secret;}
export async function GET(req:Request){try{const isAdmin=admin(req);const data=await getDb().select().from(entries).where(isAdmin?undefined:eq(entries.approved,1)).orderBy(desc(entries.created)).limit(500);return Response.json({data,isAdmin});}catch{return Response.json({error:'The league archive is unavailable. Please try again shortly.'},{status:503});}}
export async function POST(req:Request){try{if(req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Invalid origin'},{status:403});const user=await getChatGPTUser();const isAdmin=admin(req);if(!user&&!isAdmin)return Response.json({error:'Sign in to submit a post.'},{status:401});const raw=await req.text();if(raw.length>50000)return Response.json({error:'Post is too long.'},{status:400});const data=JSON.parse(raw);const {kind,title,body}=data;if(!['qualifying','race','notice','video','story'].includes(kind)||typeof title!=='string'||!title.trim()||title.length>150||typeof body!=='string'||body.length>40000)throw Error('Check the title and content.');if(['qualifying','race','notice'].includes(kind)&&!isAdmin)return Response.json({error:'Race control access required.'},{status:403});if(kind==='qualifying'||kind==='race'){if(roundNumber(title)<1||roundNumber(title)>24)throw Error('Include Round 1 to Round 24 in the title.');const rows=JSON.parse(body);if(!Array.isArray(rows)||!rows.length||rows.length>100||rows.some(r=>typeof r.driver!=='string'||!r.driver.trim()||typeof r.team!=='string'||(kind==='race'&&(!Number.isFinite(r.points)||r.points<0))||(kind==='qualifying'&&(!Number.isFinite(r.ms)||r.ms<=0||!Number.isInteger(r.attempts)||r.attempts<1||r.attempts>3))))throw Error('Invalid result rows.');if(new Set(rows.map(r=>canonical(r.driver).toLowerCase())).size!==rows.length)throw Error('A driver can only appear once. Shawn and Atlegang are the same driver.');}if(kind==='video'){const video=JSON.parse(body);const url=new URL(video.url);if(url.protocol!=='https:')throw Error('Use an HTTPS video link.');}if(['qualifying','race'].includes(kind)){const existing=await getDb().select().from(entries).where(eq(entries.kind,kind));const match=existing.find(e=>roundNumber(e.title)===roundNumber(title));if(data.replace){if((match?.id??null)!==data.expectedId||(match?.body??null)!==data.expectedBody)return Response.json({error:'This result changed since you opened it. Reset and review the latest version before saving.'},{status:409});if(match){const updated=await getDb().update(entries).set({title:title.trim(),body}).where(and(eq(entries.id,match.id),eq(entries.body,data.expectedBody)));if(!updated.meta.changes)return Response.json({error:'The result changed while saving. Reset and review the latest version.'},{status:409});return Response.json({ok:true});}}else if(match)throw Error('This round already has a classification. Open it in the result manager to edit.');}const id=['qualifying','race'].includes(kind)?`result-${kind}-${roundNumber(title)}`:crypto.randomUUID();await getDb().insert(entries).values({id,kind,title:title.trim(),body,author:isAdmin?'Race Control':user!.displayName,userId:user?.userId??'race-control',approved:isAdmin?1:0,created:new Date().toISOString()});return Response.json({ok:true});}catch(e){return Response.json({error:e instanceof Error?e.message:'Unable to save post.'},{status:400});}}
export async function PATCH(req:Request){if(req.headers.get('origin')!==new URL(req.url).origin||!admin(req))return Response.json({error:'Race control access required.'},{status:403});const {id,action}=await req.json() as {id:string,action:string};if(action==='approve')await getDb().update(entries).set({approved:1}).where(eq(entries.id,id));else if(action==='delete')await getDb().delete(entries).where(eq(entries.id,id));else return Response.json({error:'Invalid action'},{status:400});return Response.json({ok:true});}
