'use client';
import {useState} from 'react';
import {Check,Plus,Trash2,RefreshCw} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {ResultEditor} from './result-editor';
import type {League,Entry} from './league';

export function PublishingDesk({league,onAnnounce,onDelete,onApprove}:{league:League;onAnnounce:()=>void;onDelete:(id:string)=>void;onApprove:(id:string)=>Promise<void>}){
 const [search,setSearch]=useState(''),[busy,setBusy]=useState('');
 const posts=league.data.filter(e=>!e.id.startsWith('archive-')&&!['race','qualifying'].includes(e.kind));
 const pending=posts.filter(e=>!e.approved),published=posts.filter(e=>e.approved);
 async function approve(id:string){setBusy(id);try{await onApprove(id)}finally{setBusy('')}}
 function list(entries:Entry[],review:boolean){const visible=entries.filter(e=>`${e.title} ${e.author} ${e.kind}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.created.localeCompare(a.created));return <>{!visible.length?<div className="empty"><Check/><h3>{search?'No matching posts':review?'You’re all caught up':'No published posts yet'}</h3><p>{search?'Try another title or driver name.':review?'New driver stories and videos will appear here for approval.':'Post an announcement or approve a community submission.'}</p></div>:visible.map(e=>{let text=e.body,url='';if(e.kind==='video'){try{const video=JSON.parse(e.body);text=video.notes||'';if(typeof video.url==='string'&&video.url.startsWith('https://'))url=video.url}catch{text='Video details could not be read.'}}return <article className="review desk-post" key={e.id}><div><span className="eyebrow">{e.kind==='story'?'Driver story':e.kind==='notice'?'Announcement':'Video'} · {review?'Awaiting review':'Published'}</span><h4>{e.title}</h4><p className="footnote">{e.author} · {new Date(e.created).toLocaleDateString()}</p><p className="storybody">{text}</p>{url&&<a className="outline" href={url} target="_blank" rel="noopener noreferrer">Open video ↗</a>}</div><div className="formactions">{review&&<button className="primary" disabled={!!busy} onClick={()=>approve(e.id)}><Check size={16}/>{busy===e.id?'Approving…':'Approve & publish'}</button>}<button className="outline" disabled={!!busy} onClick={()=>onDelete(e.id)}><Trash2 size={16}/>{review?'Reject & delete':'Delete'}</button></div></article>})}</>}
 return <div className="publishing-workspace"><div className="desk-overview"><div><strong>{pending.length}</strong><span>Awaiting review</span></div><div><strong>{league.data.filter(e=>e.kind==='race'&&e.approved).length}</strong><span>Race classifications</span></div><div><strong>{league.data.filter(e=>e.kind==='qualifying'&&e.approved).length}</strong><span>Qualifying classifications</span></div></div><div className="sectionhead desk-actions"><p className="muted">Publish classifications, review the paddock and keep drivers informed.</p><button className="outline" disabled={!!busy} onClick={async()=>{setBusy('refresh');try{await league.refresh()}finally{setBusy('')}}}><RefreshCw size={16}/>{busy==='refresh'?'Refreshing…':'Refresh'}</button></div>{league.error&&<p role="alert">{league.error}</p>}<Tabs defaultValue="results"><TabsList className="desk-tabs"><TabsTrigger value="results">Results</TabsTrigger><TabsTrigger value="review">Review queue ({pending.length})</TabsTrigger><TabsTrigger value="published">Published posts</TabsTrigger></TabsList><TabsContent value="results" keepMounted><ResultEditor league={league}/></TabsContent><TabsContent value="review"><div className="sectionhead"><div><h3>Review driver submissions</h3><p className="muted">Only approved posts are visible to everyone.</p></div><input aria-label="Search pending submissions" placeholder="Search title or driver…" value={search} onChange={e=>setSearch(e.target.value)}/></div>{list(pending,true)}</TabsContent><TabsContent value="published"><div className="sectionhead"><div><h3>Announcements & community posts</h3><p className="muted">Manage race-control notices, stories and videos.</p></div><button className="primary" onClick={onAnnounce}><Plus size={16}/>New announcement</button></div><input className="desk-search" aria-label="Search published posts" placeholder="Search title or driver…" value={search} onChange={e=>setSearch(e.target.value)}/>{list(published,false)}</TabsContent></Tabs></div>
}
