'use client';
import {useState} from 'react';
import {Download,ImageIcon,Copy} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {formatLap,gap,sortQual,type QualRow} from './result-utils';
import {schedule} from './season';
export function drawQualifyingCard(canvas:HTMLCanvasElement,round:number,input:QualRow[],partial:boolean,count:number){
 const rows=sortQual(input);canvas.width=1200;canvas.height=350+rows.length*92;const c=canvas.getContext('2d');if(!c)throw Error('Image export is not supported by this browser.');
 c.fillStyle='#0b101b';c.fillRect(0,0,canvas.width,canvas.height);c.fillStyle='#ff443d';c.fillRect(0,0,1200,12);
 const write=(s:string,x:number,y:number,size=22,color='#f1f3f8',bold=false,max=1100)=>{c.fillStyle=color;c.font=`${bold?'700':'400'} ${size}px Arial`;while(c.measureText(s).width>max&&s.length>1)s=s.slice(0,-2)+'…';c.fillText(s,x,y)};
 write('RLS1  /  SEASON 01',50,64,22,'#b5c2d6',true);write('QUALIFYING RESULTS',50,124,46,'#ffffff',true);
 write(`ROUND ${String(round).padStart(2,'0')}  ·  ${schedule[round-1].country.toUpperCase()}`,50,172,27,'#ff6b63',true);
 write(partial?`ANNOUNCEMENT SUMMARY · ${count} DRIVERS · MISSING TIMES SHOWN AS —`:`FINAL CLASSIFICATION · ${rows.length} DRIVERS`,50,246,16,'#b5c2d6',true);
 const xs=[50,155,675,800,1030];['POS','DRIVER / TEAM','ATTEMPTS','BEST LAP','GAP'].forEach((s,i)=>write(s,xs[i],288,15,'#8ea0b8',true));
 rows.forEach((r,i)=>{const y=310+i*92;c.fillStyle=i===0?'#282039':i%2?'#101826':'#151f2e';c.fillRect(30,y-4,1140,86);c.fillStyle=i===0?'#bc95ff':'#ff443d';c.fillRect(30,y-4,4,86);write(String(i+1).padStart(2,'0'),50,y+47,30,i===0?'#d7bfff':'#e2e8f2',true);write(r.driver,155,y+31,25,'#ffffff',true,470);write(r.team||'Team not supplied',155,y+61,17,'#a7b6ca',false,470);write(r.attempts?`${r.attempts}/3`:'—',675,y+42,22);write(r.ms?formatLap(r.ms):'—',800,y+42,25,i===0?'#d7bfff':'#f1f3f8',true);write(r.ms&&rows[0]?.ms?gap(r.ms,rows[0].ms):'—',1030,y+42,20,'#bcc9da');});
 write(partial?'Partial archive · only supplied positions and times are shown':'RLS1 eSports  ·  Race Control',50,canvas.height-16,16,'#8ea0b8');
 return canvas;
}
export function QualifyingCard({round,rows,partial=false,count=rows.length}:{round:number;rows:QualRow[];partial?:boolean;count?:number}){
 const [preview,setPreview]=useState(''),[status,setStatus]=useState('');const grid=sortQual(rows);
 function image(){try{const canvas=drawQualifyingCard(document.createElement('canvas'),round,grid,partial,count);setPreview(canvas.toDataURL('image/png'));setStatus('')}catch(e){setStatus((e as Error).message)}}
 async function copy(){try{await navigator.clipboard.writeText(`🏁 QUALIFYING RESULTS — RLS1\nSeason 1 — Round ${round}: ${schedule[round-1].country}\n${partial?'Announcement summary':'Final classification'}\n\n`+grid.map((r,i)=>`${i+1}. ${r.driver} | ${r.ms?formatLap(r.ms):'Time not supplied'} | ${r.ms&&grid[0].ms?gap(r.ms,grid[0].ms):'—'}`).join('\n'));setStatus('Qualifying recap copied.')}catch{setStatus('Copy failed. Use the image download instead.')}}
 return <section className="panel qualifying-panel"><div className="sectionhead"><div><p className="eyebrow">THE STARTING GRID</p><h3>Qualifying results</h3></div><span className={'badge '+(!partial?'verified':'')}>{partial?'Announcement summary':'Full classification'}</span></div>{grid.length?<><div className="qualstats"><div><span>POLE POSITION</span><strong>{grid[0].driver}</strong></div><div><span>BEST LAP</span><strong className="purple">{grid[0].ms?formatLap(grid[0].ms):'—'}</strong></div><div><span>DRIVERS</span><strong>{count}</strong></div></div><Table><TableHeader><TableRow>{['POS','DRIVER / TEAM','ATTEMPTS','BEST LAP','GAP'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{grid.map((r,i)=><TableRow key={i}><TableCell className={'position p'+i}>{i+1}</TableCell><TableCell><strong>{r.driver}</strong><small className="team">{r.team||'Team not supplied'}</small></TableCell><TableCell>{r.attempts?`${r.attempts}/3`:'—'}</TableCell><TableCell className="time">{r.ms?formatLap(r.ms):'—'}</TableCell><TableCell>{r.ms&&grid[0].ms?gap(r.ms,grid[0].ms):'—'}</TableCell></TableRow>)}</TableBody></Table><div className="formactions"><button className="primary" onClick={image}><ImageIcon size={17}/>Save qualifying picture</button><button className="outline" onClick={copy}><Copy size={16}/>Copy Discord recap</button></div>{partial&&<p className="footnote">Only the supplied positions and pole time are shown. Publish the full qualifying results in Race control to replace this summary.</p>}</>:<p className="muted">No qualifying classification published for this round.</p>}<p role="status">{status}</p><Dialog open={!!preview} onOpenChange={v=>!v&&setPreview('')}><DialogContent className="qual-preview"><DialogTitle>Ready for Discord</DialogTitle><DialogDescription>A 1200 px PNG with the qualifying classification for Round {round}.</DialogDescription>{preview&&<img src={preview} alt={`Qualifying results graphic for round ${round}`}/>}<a className="primary" href={preview} download={`RLS1-S1-R${round}-qualifying.png`}><Download size={17}/>Download PNG</a></DialogContent></Dialog></section>
}
